"""Constants for Warema WMS WebControl pro."""

DOMAIN = "warema_wms"

CONF_HOST = "host"
CONF_PORT = "port"

SCAN_INTERVAL = 30

PROTOCOL_VERSION = "1.0"
SOURCE_ID = 2

ANIMATION_TYPE_VENETIAN_BLIND = 0
ANIMATION_TYPE_AWNING = 1
ANIMATION_TYPE_ROLLER_SHUTTER = 2
ANIMATION_TYPE_SLAT_ROOF = 3
ANIMATION_TYPE_WINDOW = 4
ANIMATION_TYPE_SWITCH = 5
ANIMATION_TYPE_DIMMER = 6
ANIMATION_TYPE_UNKNOWN = 999

ANIMATION_TYPE_NAMES = {
    0: "Venetian Blind",
    1: "Awning",
    2: "Roller Shutter",
    3: "Slat Roof (Lamaxa)",
    4: "Window",
    5: "Switch",
    6: "Dimmer",
    999: "Unknown",
}

ACTION_TYPE_PERCENTAGE = 0
ACTION_TYPE_PERCENTAGE_DELTA = 1
ACTION_TYPE_ROTATION = 2
ACTION_TYPE_ROTATION_DELTA = 3
ACTION_TYPE_SWITCH = 4
ACTION_TYPE_TOGGLE = 5
ACTION_TYPE_STOP = 6
ACTION_TYPE_IMPULSE = 7
ACTION_TYPE_IDENTIFY = 8
ACTION_TYPE_ENUMERATION = 9

COVER_ANIMATION_TYPES = {0, 1, 2, 3, 4}
TILT_ANIMATION_TYPES = {0, 3}

